### ISSUE TITLE
Implement confirmation-thank-you page 

### ISSUE THREAD

**Issue by acidjunk** [acidjunk/improviser#9]
Implement an page to show the user a thank-you dialog when the e-mail confirmation link was clicked.

As noted by Bert :)

**Comment by guusdohmen** [comment]
Wat is dit?

Op ma 11 feb. 2019 20:35 schreef Rene Dohmen <notifications@github.com:

**Comment by acidjunk** [comment]
Added a redirect from confirmation page to the improviser SPA.
